<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "upload_example"
 *
 * Auto generated by Extension Builder 19-02-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TypoScript Rendering',
	'description' => 'Can render a TypoScript snippet by URL',
	'category' => 'Example Extensions',
	'author' => 'Helmut Hummel',
	'author_email' => 'info@helmut-hummel.de',
	'author_company' => 'Helmut Hummel',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'php' => '5.3.7-5.5.999',
			'typo3' => '6.2.3-6.3.999',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>